//
//  CPManagedObjectModel+XCDataModel.j
//
//  Created by Raphael Bartolome on 23.11.09.
//
//  Enhanced to support the Xcode 4+ XML-based CoreData model format
//  (.xcdatamodel/contents and .xcdatamodeld bundles).
//
//  Old format (.cxcdatamodel):  XML property-list encoded with NSKeyedArchiver,
//                               decoded via CPKeyedUnarchiver.
//
//  New format (.xcdatamodel/contents):  Plain XML file generated by Xcode 4+.
//  New bundle  (.xcdatamodeld):         Directory wrapping versioned .xcdatamodel
//                                        packages; the active version is named in
//                                        .xccurrentversion.
//

@import <Foundation/Foundation.j>


@implementation CPManagedObjectModel (XCDataModel)

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/*!
    Load a CoreData model from a .xcdatamodel path.

    The method first tries the new Xcode 4+ XML format by checking for a
    "contents" file inside the .xcdatamodel directory.  If that request returns
    nothing it falls back to the old .cxcdatamodel binary property list.

    @param aModelName  URL / file-system path of the .xcdatamodel resource.
*/
+ (CPManagedObjectModel) parseCoreDataModel:(CPString) aModelName
{
    // --- Try new XML format: <modelPath>/contents ----------------------------
    if ([aModelName hasSuffix:@"xcdatamodel"])
    {
        var contentsURL = aModelName + @"/contents";
        var contentsData = [CPURLConnection sendSynchronousRequest:
                                [CPURLRequest requestWithURL:contentsURL]
                                              returningResponse:nil];
        if (contentsData !== nil)
        {
            var xmlString = [contentsData rawString];
            if ([self _isXCDataModelXML:xmlString])
            {
                var model = [self _parseContentsXML:xmlString];
                [model setNameFromFilePath:aModelName];
                return model;
            }
        }
    }

    // --- Fall back to old .cxcdatamodel format --------------------------------
    var modelPath = aModelName;
    if (![modelPath hasSuffix:@"cxcdatamodel"])
    {
        var modelNameComponents = [modelPath componentsSeparatedByString:@"."];
        modelPath = [modelNameComponents objectAtIndex:0] + @".cxcdatamodel";
    }

    var data = [CPURLConnection sendSynchronousRequest:
                    [CPURLRequest requestWithURL:modelPath]
                                  returningResponse:nil];
    var plistContents = [data rawString].replace(/\<key\>\s*CF\$UID\s*\<\/key\>/g,
                                                 "<key>CP$UID</key>");
    var unarchiver = [[CPKeyedUnarchiver alloc]
                            initForReadingWithData:[CPData dataWithRawString:plistContents]];

    var managedObjectModel = [unarchiver decodeObjectForKey:@"root"];
    [managedObjectModel setNameFromFilePath:modelPath];
    return managedObjectModel;
}

/*!
    Asynchronously load a CoreData model from a .xcdatamodel path.

    Uses CPURLConnection async API so the browser UI is not blocked.  The
    delegate receives one of:
      - managedObjectModelDidFinishLoading:(CPManagedObjectModel) — on success
      - managedObjectModelDidFailToLoad:(CPString)              — on failure

    @param aModelName  URL / file-system path of the .xcdatamodel resource.
    @param aDelegate   Object implementing the informal delegate protocol above.
    @return The CPXCDataModelLoader driving the request (may be ignored).
*/
+ (id) parseCoreDataModelAsync:(CPString)aModelName
                      delegate:(id)aDelegate
{
    var loader = [CPXCDataModelLoader loaderWithModelPath:aModelName
                                                 delegate:aDelegate];
    [loader start];
    return loader;
}

/*!
    Load a CoreData model from a .xcdatamodeld bundle.

    The bundle contains one or more versioned .xcdatamodel packages.  The
    active version is stored in the optional .xccurrentversion plist file;
    if that file is absent the bundle base name is used.

    @param aModelName  URL / file-system path of the .xcdatamodeld resource.
*/
+ (CPManagedObjectModel) parseXCDataModelBundle:(CPString) aModelName
{
    // Determine the active model name (default: bundle base name)
    var nameComponents    = [aModelName componentsSeparatedByString:@"."],
        pathComponents    = [[nameComponents objectAtIndex:0] componentsSeparatedByString:@"/"],
        baseName          = [pathComponents lastObject],
        activeModelName   = baseName;

    // Try to read .xccurrentversion to find the current version
    var versionURL  = aModelName + @"/.xccurrentversion",
        versionData = [CPURLConnection sendSynchronousRequest:
                           [CPURLRequest requestWithURL:versionURL]
                                         returningResponse:nil];
    if (versionData !== nil)
    {
        var versionStr = [versionData rawString];
        if (versionStr !== nil)
        {
            // Xcode writes an XML plist; the current version file name is under
            // the _XCCurrentVersionName key.
            var match = versionStr.match(
                            /<key>_XCCurrentVersionName<\/key>\s*<string>([^<]+)<\/string>/);
            if (match && match[1])
            {
                // Strip the .xcdatamodel extension to get the plain name
                var versionFile = match[1];
                var versionParts = [versionFile componentsSeparatedByString:@"."];
                activeModelName = [versionParts objectAtIndex:0];
            }
        }
    }

    // Load the contents file from the active .xcdatamodel inside the bundle
    var contentsURL = aModelName + @"/" + activeModelName + @".xcdatamodel/contents",
        contentsData = [CPURLConnection sendSynchronousRequest:
                            [CPURLRequest requestWithURL:contentsURL]
                                          returningResponse:nil];

    if (contentsData !== nil)
    {
        var xmlString = [contentsData rawString];
        if ([self _isXCDataModelXML:xmlString])
        {
            var model = [self _parseContentsXML:xmlString];
            [model setNameFromFilePath:aModelName];
            return model;
        }
    }

    CPLog.warn(@"CPManagedObjectModel: could not load model bundle at " + aModelName);
    return [[CPManagedObjectModel alloc] init];
}

/*!
    Asynchronously load a CoreData model from a .xcdatamodeld bundle.

    Uses CPURLConnection async API so the browser UI is not blocked.  The
    delegate receives one of:
      - managedObjectModelDidFinishLoading:(CPManagedObjectModel) — on success
      - managedObjectModelDidFailToLoad:(CPString)              — on failure

    @param aModelName  URL / file-system path of the .xcdatamodeld resource.
    @param aDelegate   Object implementing the informal delegate protocol above.
    @return The CPXCDataModelLoader driving the request (may be ignored).
*/
+ (id) parseXCDataModelBundleAsync:(CPString)aModelName
                          delegate:(id)aDelegate
{
    var loader = [CPXCDataModelLoader loaderWithModelPath:aModelName
                                                 delegate:aDelegate];
    [loader start];
    return loader;
}


// ---------------------------------------------------------------------------
// XML contents parser
// ---------------------------------------------------------------------------

/*!
    Returns YES if the given string looks like an Xcode 4+ CoreData model XML
    document (contains a '<model' element).  Used to distinguish the new XML
    format from an empty or error response.
*/
+ (BOOL) _isXCDataModelXML:(CPString) xmlString
{
    return xmlString !== nil && xmlString !== null
        && xmlString.indexOf("<model") >= 0;
}

/*!
    Parse the XML contents of a Xcode 4+ .xcdatamodel/contents file and
    return a populated CPManagedObjectModel.

    The DOM is built using the browser's native DOMParser; in non-browser
    environments (e.g. test runners) parsing is skipped gracefully and an
    empty model is returned.

    @param xmlString  Raw XML string from the contents file.
*/
+ (CPManagedObjectModel) _parseContentsXML:(CPString) xmlString
{
    var model = [[CPManagedObjectModel alloc] init];

    if (typeof DOMParser === "undefined" && typeof ActiveXObject === "undefined")
    {
        CPLog.warn(@"CPManagedObjectModel: DOMParser not available; skipping XML model parse");
        return model;
    }

    var dom = _CPXMLDocumentFromString(xmlString);
    if (!dom)
    {
        CPLog.error(@"CPManagedObjectModel: failed to parse CoreData model XML");
        return model;
    }

    var modelElements = dom.getElementsByTagName("model");
    if (!modelElements || modelElements.length === 0)
    {
        CPLog.warn(@"CPManagedObjectModel: no <model> element found in contents");
        return model;
    }

    var modelEl   = modelElements.item(0),
        entityEls = modelEl.getElementsByTagName("entity");

    // --- First pass: create all entity stubs --------------------------------
    for (var i = 0; i < entityEls.length; i++)
    {
        var entityEl = entityEls.item(i);
        if (entityEl.parentNode !== modelEl) continue; // direct children only

        var entityName = entityEl.getAttribute("name");
        if (!entityName) continue;

        var entity = [[CPEntityDescription alloc] init];
        [entity setName:entityName];
        [model addEntity:entity];
    }

    // --- Second pass: add attributes and relationships ---------------------
    for (var i = 0; i < entityEls.length; i++)
    {
        var entityEl = entityEls.item(i);
        if (entityEl.parentNode !== modelEl) continue;

        var entityName = entityEl.getAttribute("name");
        if (!entityName) continue;

        var entity = [model entityWithName:entityName];

        // Attributes
        var attrEls = entityEl.getElementsByTagName("attribute");
        for (var j = 0; j < attrEls.length; j++)
        {
            var attrEl = attrEls.item(j);
            if (attrEl.parentNode !== entityEl) continue;

            var attrName = attrEl.getAttribute("name");
            if (!attrName) continue;

            var attrType   = attrEl.getAttribute("attributeType") || @"",
                optional   = (attrEl.getAttribute("optional") === "YES"),
                typeValue  = [self _attributeTypeForXCDataModelType:attrType],
                classValue = [self _classValueForXCDataModelType:attrType];

            [entity addAttributeWithName:attrName
                               classValue:classValue
                               typeValue:typeValue
                                optional:optional];
        }

        // Relationships
        var relEls = entityEl.getElementsByTagName("relationship");
        for (var j = 0; j < relEls.length; j++)
        {
            var relEl = relEls.item(j);
            if (relEl.parentNode !== entityEl) continue;

            var relName = relEl.getAttribute("name");
            if (!relName) continue;

            var destination   = relEl.getAttribute("destinationEntity") || @"",
                toMany        = (relEl.getAttribute("toMany") === "YES"),
                optional      = (relEl.getAttribute("optional") === "YES"),
                deleteRuleStr = relEl.getAttribute("deletionRule") || @"Nullify",
                deleteRule    = [self _deleteRuleForXCDataModelString:deleteRuleStr];

            [entity addRelationshipWithName:relName
                                     toMany:toMany
                                   optional:optional
                                 deleteRule:deleteRule
                                destination:destination];
        }
    }

    return model;
}


// ---------------------------------------------------------------------------
// Type / rule mapping helpers
// ---------------------------------------------------------------------------

/*!
    Map an Xcode attributeType string to the corresponding CPD*AttributeType
    integer constant.
*/
+ (int) _attributeTypeForXCDataModelType:(CPString) attrType
{
    if ([attrType isEqualToString:@"String"])         return CPDStringAttributeType;
    if ([attrType isEqualToString:@"Integer 16"])      return CPDInteger16AttributeType;
    if ([attrType isEqualToString:@"Integer 32"])      return CPDInteger32AttributeType;
    if ([attrType isEqualToString:@"Integer 64"])      return CPDInteger64AttributeType;
    if ([attrType isEqualToString:@"Float"])           return CPDFloatAttributeType;
    if ([attrType isEqualToString:@"Double"])          return CPDDoubleAttributeType;
    if ([attrType isEqualToString:@"Decimal"])         return CPDDecimalAttributeType;
    if ([attrType isEqualToString:@"Boolean"])         return CPDBooleanAttributeType;
    if ([attrType isEqualToString:@"Date"])            return CPDDateAttributeType;
    if ([attrType isEqualToString:@"Binary Data"])     return CPDBinaryDataAttributeType;
    if ([attrType isEqualToString:@"Transformable"])   return CPDTransformableAttributeType;
    return CPDUndefinedAttributeType;
}

/*!
    Map an Xcode attributeType string to the Cappuccino class name used to
    store values of that type.
*/
+ (CPString) _classValueForXCDataModelType:(CPString) attrType
{
    if ([attrType isEqualToString:@"String"])   return @"CPString";
    if ([attrType isEqualToString:@"Date"])     return @"CPDate";
    if ([attrType isEqualToString:@"Binary Data"]) return @"CPData";
    if ([attrType isEqualToString:@"Transformable"]) return @"CPObject";
    if ([attrType isEqualToString:@"UUID"])     return @"CPString";
    if ([attrType isEqualToString:@"URI"])      return @"CPURL";
    // All numeric and boolean types map to CPNumber
    if (   [attrType isEqualToString:@"Integer 16"]
        || [attrType isEqualToString:@"Integer 32"]
        || [attrType isEqualToString:@"Integer 64"]
        || [attrType isEqualToString:@"Float"]
        || [attrType isEqualToString:@"Double"]
        || [attrType isEqualToString:@"Decimal"]
        || [attrType isEqualToString:@"Boolean"])
    {
        return @"CPNumber";
    }
    return @"CPString";
}

/*!
    Map an Xcode deletionRule string to the corresponding
    CPRelationshipDescriptionDeleteRule* integer constant.
*/
+ (int) _deleteRuleForXCDataModelString:(CPString) ruleString
{
    if ([ruleString isEqualToString:@"Cascade"])    return CPRelationshipDescriptionDeleteRuleCascade;
    if ([ruleString isEqualToString:@"Deny"])       return CPRelationshipDescriptionDeleteRuleDeny;
    if ([ruleString isEqualToString:@"No Action"])  return CPRelationshipDescriptionDeleteRuleNoAction;
    return CPRelationshipDescriptionDeleteRuleNullify; // default
}

@end


// ---------------------------------------------------------------------------
// Private helper: parse XML string into a DOM document
// ---------------------------------------------------------------------------

var _CPXMLDocumentFromString = function(anXMLString)
{
    try
    {
        if (typeof ActiveXObject !== "undefined")
        {
            var XMLDoc = new ActiveXObject("Microsoft.XMLDOM");
            XMLDoc.async = false;
            XMLDoc.loadXML(anXMLString);
            return XMLDoc;
        }
        return new DOMParser().parseFromString(anXMLString, "text/xml");
    }
    catch (e)
    {
        CPLog.error(@"CPManagedObjectModel+XCDataModel: XML parse error: " + e);
        return nil;
    }
};


// Phase constants for CPXCDataModelLoader state machine
var CPXCLoaderPhaseNewXMLContents = @"new_xml_contents";
var CPXCLoaderPhaseOldPlist       = @"old_plist";
var CPXCLoaderPhaseBundleVersion  = @"bundle_version";
var CPXCLoaderPhaseBundleContents = @"bundle_contents";


// ---------------------------------------------------------------------------
// CPXCDataModelLoader
//
// Async helper class that mirrors the role of CPManagedObjectModelLoader in
// CPManagedObjectModel+JSONSchema.j but targets the XCDataModel format.
//
// Delegate informal protocol (required):
//   - (void)managedObjectModelDidFinishLoading:(CPManagedObjectModel)model
//
// Delegate informal protocol (optional):
//   - (void)managedObjectModelDidFailToLoad:(CPString)modelPath
//
// Loading state machine for .xcdatamodel:
//   CPXCLoaderPhaseNewXMLContents → try <path>/contents
//     success + XML  → parse, notify delegate
//     failure / not XML → CPXCLoaderPhaseOldPlist: try <baseName>.cxcdatamodel
//   CPXCLoaderPhaseOldPlist
//     success → decode with CPKeyedUnarchiver, notify delegate
//     failure → notify failure
//
// Loading state machine for .xcdatamodeld:
//   CPXCLoaderPhaseBundleVersion → try <path>/.xccurrentversion
//     success or failure → extract version name, fall through to …
//   CPXCLoaderPhaseBundleContents → try <path>/<version>.xcdatamodel/contents
//     success + XML → parse, notify delegate
//     failure → notify failure
// ---------------------------------------------------------------------------

@implementation CPXCDataModelLoader : CPObject
{
    CPString _modelPath;
    id       _delegate;
    CPString _phase;
    CPString _dataReceived;
    int      _statusReceived;
}

+ (CPXCDataModelLoader) loaderWithModelPath:(CPString)aModelPath
                                   delegate:(id)aDelegate
{
    var loader = [[CPXCDataModelLoader alloc] init];
    loader._modelPath = aModelPath;
    loader._delegate  = aDelegate;
    return loader;
}

- (void) start
{
    if ([_modelPath hasSuffix:@"xcdatamodeld"])
    {
        // .xcdatamodeld bundle: first try .xccurrentversion
        [self _fetchURL:_modelPath + @"/.xccurrentversion"
                  phase:CPXCLoaderPhaseBundleVersion];
    }
    else
    {
        // .xcdatamodel: try new XML contents first
        [self _fetchURL:_modelPath + @"/contents"
                  phase:CPXCLoaderPhaseNewXMLContents];
    }
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

- (void) _fetchURL:(CPString)url phase:(CPString)phase
{
    _phase = phase;
    _dataReceived = @"";
    _statusReceived = 0;
    var request = [CPURLRequest requestWithURL:url];
    [CPURLConnection connectionWithRequest:request delegate:self];
}

- (void) _notifySuccess:(CPManagedObjectModel)model
{
    if ([_delegate respondsToSelector:@selector(managedObjectModelDidFinishLoading:)])
        [_delegate managedObjectModelDidFinishLoading:model];
}

- (void) _notifyFailure
{
    CPLog.warn(@"CPXCDataModelLoader: could not load model at " + _modelPath);
    if ([_delegate respondsToSelector:@selector(managedObjectModelDidFailToLoad:)])
        [_delegate managedObjectModelDidFailToLoad:_modelPath];
}

// ---------------------------------------------------------------------------
// CPURLConnection delegate
// ---------------------------------------------------------------------------

- (void) connection:(CPURLConnection)connection
    didReceiveResponse:(CPHTTPURLResponse)response
{
    _statusReceived = [response statusCode];
    _dataReceived   = @"";
}

- (void) connection:(CPURLConnection)connection
      didReceiveData:(id)data
{
    _dataReceived = [_dataReceived stringByAppendingString:data];
}

- (void) connectionDidFinishLoading:(CPURLConnection)connection
{
    var ok = (_statusReceived == 200);

    if (_phase === CPXCLoaderPhaseNewXMLContents)
    {
        if (ok && [CPManagedObjectModel _isXCDataModelXML:_dataReceived])
        {
            var model = [CPManagedObjectModel _parseContentsXML:_dataReceived];
            [model setNameFromFilePath:_modelPath];
            [self _notifySuccess:model];
        }
        else
        {
            // Fall back to old .cxcdatamodel format
            var parts   = [_modelPath componentsSeparatedByString:@"."];
            var oldPath = [parts objectAtIndex:0] + @".cxcdatamodel";
            [self _fetchURL:oldPath phase:CPXCLoaderPhaseOldPlist];
        }
    }
    else if (_phase === CPXCLoaderPhaseOldPlist)
    {
        if (ok && _dataReceived !== nil && [_dataReceived length] > 0)
        {
            var plist = _dataReceived.replace(
                            /\<key\>\s*CF\$UID\s*\<\/key\>/g,
                            "<key>CP$UID</key>");
            var unarchiver = [[CPKeyedUnarchiver alloc]
                                    initForReadingWithData:[CPData dataWithRawString:plist]];
            var model = [unarchiver decodeObjectForKey:@"root"];
            [model setNameFromFilePath:_modelPath];
            [self _notifySuccess:model];
        }
        else
        {
            [self _notifyFailure];
        }
    }
    else if (_phase === CPXCLoaderPhaseBundleVersion)
    {
        // Determine the active model name
        var activeModelName = nil;
        if (ok && _dataReceived !== nil)
        {
            var match = _dataReceived.match(
                            /<key>_XCCurrentVersionName<\/key>\s*<string>([^<]+)<\/string>/);
            if (match && match[1])
            {
                var versionParts = [match[1] componentsSeparatedByString:@"."];
                activeModelName = [versionParts objectAtIndex:0];
            }
        }
        if (activeModelName == nil)
        {
            // Fall back to the bundle base name
            var dotParts  = [_modelPath componentsSeparatedByString:@"."];
            var slashParts = [[dotParts objectAtIndex:0] componentsSeparatedByString:@"/"];
            activeModelName = [slashParts lastObject];
        }
        var contentsURL = _modelPath + @"/" + activeModelName + @".xcdatamodel/contents";
        [self _fetchURL:contentsURL phase:CPXCLoaderPhaseBundleContents];
    }
    else if (_phase === CPXCLoaderPhaseBundleContents)
    {
        if (ok && [CPManagedObjectModel _isXCDataModelXML:_dataReceived])
        {
            var model = [CPManagedObjectModel _parseContentsXML:_dataReceived];
            [model setNameFromFilePath:_modelPath];
            [self _notifySuccess:model];
        }
        else
        {
            [self _notifyFailure];
        }
    }
}

- (void) connection:(CPURLConnection)connection
   didFailWithError:(id)error
{
    CPLog.warn(@"CPXCDataModelLoader: network error in phase '" + _phase
               + "' for " + _modelPath + ": " + error);

    if (_phase === CPXCLoaderPhaseNewXMLContents)
    {
        // Network error for new-format attempt: fall back to old format
        var parts   = [_modelPath componentsSeparatedByString:@"."];
        var oldPath = [parts objectAtIndex:0] + @".cxcdatamodel";
        [self _fetchURL:oldPath phase:CPXCLoaderPhaseOldPlist];
    }
    else if (_phase === CPXCLoaderPhaseBundleVersion)
    {
        // .xccurrentversion not reachable — try default name
        var dotParts   = [_modelPath componentsSeparatedByString:@"."];
        var slashParts = [[dotParts objectAtIndex:0] componentsSeparatedByString:@"/"];
        var defaultName = [slashParts lastObject];
        var contentsURL = _modelPath + @"/" + defaultName + @".xcdatamodel/contents";
        [self _fetchURL:contentsURL phase:CPXCLoaderPhaseBundleContents];
    }
    else
    {
        [self _notifyFailure];
    }
}

@end

