/*
 * Jakefile
 * CoreData
 *
 * Created by Raphael Bartolome on February 5, 2010.
 * 
 * The MIT License
 * 
 * Copyright (c) 2009 Raphael Bartolome
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 */

//===========================================================
//  DO NOT REMOVE
//===========================================================

const env = process.env;
const path = require("path");

//===========================================================
//  USER CONFIGURABLE VARIABLES
//===========================================================

/*
    The directory in which the project will be built. By default
    it is built in $CAPP_BUILD if that is defined, otherwise
    in a "Build" directory within the project directory.
*/

const buildDir = path.resolve(env["BUILD_PATH"] || env["CAPP_BUILD"] || "Build");

/*
    The list of directories containing Objective-J source
    that should be compiled by jake. The main framework
    directory is always checked for Objective-J source,
    you only need to edit this if you have source in
    subdirectories. Do NOT include a leading ortrailing slash
    in the directory name.

    Example:

    const sourceDirs = [
            "Core",
            "Modules",
            "Modules/Foo",
            "Modules/Bar"
        ];
*/

const sourceDirs = [
    "NSCoreData",
    "CPCoreDataCategories",
    "CPCoreDataHeaders",
    "CPCoreDataJSONSchema",
    "CPCoreDataPersistentStores",
    "CPCoreDataPersistentStores/HTML5Store",
    "CPCoreDataPersistentStores/HTTPStore",
    "CPCoreDataPersistentStores/MemoryStore",
    "CPCoreDataPersistentStores/WebDAVStore",
    "CPCoreDataPersistentStores/WOStore"
    ];

/*
    The path to where to install the framework
*/

const packageFrameworksPath = path.join("~", "Developer", "Frameworks");

//===========================================================
//  AUTOMATICALLY GENERATED
//
//  Do not edit! (unless you know what you are doing)
//===========================================================

const fs = require("fs");
const childProcess = require("child_process");

const stream = ObjectiveJ.term.stream;
const utilsFile = ObjectiveJ.utils.file;
const jake = JAKE;

const CLEAN = JAKE.CLEAN_AND_CLOBBER.CLEAN;
const CLOBBER = JAKE.CLEAN_AND_CLOBBER.CLOBBER;

const FileList = jake.FileList;
const filedir = jake.filedir;
const task = jake.task;

const framework = CAPPUCCINO.Jake.frameworktask.framework;

const configuration = env["CONFIG"] || env["CONFIGURATION"] || env["c"] || "Debug";
const productName = "CoreData";

const buildPath = path.join(buildDir, productName + ".build");
const debugPackagePath = path.join(packageFrameworksPath, "Debug", productName);
const releasePackagePath = path.join(packageFrameworksPath, productName);

const frameworkTask = framework (productName, function(frameworkTask)
{
    frameworkTask.setBuildIntermediatesPath(path.join(buildPath, configuration));
    frameworkTask.setBuildPath(path.join(buildDir, configuration));

    frameworkTask.setProductName(productName);
    frameworkTask.setIdentifier("com.rbartolome.CoreData");
    frameworkTask.setVersion("0.1");
    frameworkTask.setAuthor("Raphael Bartolome");
    frameworkTask.setEmail("raphael.bartolome@gmail.com");
    frameworkTask.setSummary("A CoreData implementation in Objective-J for Cappuccino");

    var includes = sourceDirs.map(function(dir) { 
        return dir + "/*.j"; 
    });

    const fileList = new FileList();

    includes.unshift("*.j");
    fileList.include(includes);
    frameworkTask.setSources(fileList);
    frameworkTask.setResources(new FileList("Resources/**/*"));
    frameworkTask.setFlattensSources(true);
    frameworkTask.setInfoPlistPath("Info.plist");
    frameworkTask.setLicense(BundleTask.License.MIT);

    if (configuration === "Debug") {
        frameworkTask.setCompilerFlags("-DDEBUG -g -S --inline-msg-send");
    } else {
        frameworkTask.setCompilerFlags("-O2");
    }
});

task("test", function()
{
    var tests = new FileList('Tests/*Test.j');
    var cmd = ["ojtest"].concat(tests.items());
    var cmdString = cmd.map(utilsFile.enquote).join(" ");

    childProcess.execSync(cmdString);
});

task ("debug", function()
{
    env["CONFIGURATION"] = "Debug";
    jake.subjake(["."], "build", env);
});

task ("release", function()
{
    env["CONFIGURATION"] = "Release";
    jake.subjake(["."], "build", env);
});

task ("default", ["release"]);

const frameworkCJS = path.join(buildDir, configuration, "CommonJS", "cappuccino", "Frameworks", productName);

filedir (frameworkCJS, [productName], function()
{
    if (fs.existsSync(frameworkCJS))
        fs.rmSync(frameworkCJS, { recursive: true });

    utilsFile.cp_r(frameworkTask.buildProductPath(), frameworkCJS);
});

const esbuild = require("esbuild");

task("copy-vendor", async function()
{
    if (!fs.existsSync("Resources"))
        fs.mkdirSync("Resources");

    await esbuild.build({
        entryPoints: [require.resolve("jsv")],
        bundle: true,           // inlines all require()s
        format: "iife",         // self-contained, no module system needed
        globalName: "JSV",      // exposes as window.JSV / global.JSV
        outfile: path.join("Resources", "JSV.js"),
        platform: "browser",
    });

    console.log("Bundled JSV.js to Resources/");
});

// Make the main build depend on vendor copy
task("build", ["copy-vendor", productName, frameworkCJS]);

task ("all", ["debug", "release"]);

task ("install", ["debug", "release"], function()
{
    install("copy");
});

task ("install-symlinks", ["debug", "release"], function()
{
    install("symlink");
});

task ("docs", ["documentation"]);

task ("documentation", function()
{
    // try to find a doxygen executable in the PATH;
    var doxygen = executableExists("doxygen");

    // If the Doxygen application is installed on Mac OS X, use that
    if (!doxygen && executableExists("mdfind"))
    {
        var p = OS.popen(["mdfind", "kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == 'org.doxygen'"]);
        if (p.wait() === 0)
        {
            var doxygenApps = p.stdout.read().split("\n");
            if (doxygenApps[0])
                doxygen = FILE.join(doxygenApps[0], "Contents/Resources/doxygen");
        }
    }

    if (doxygen && FILE.exists(doxygen))
    {
        stream.print("\0green(Using " + doxygen + " for doxygen binary.\0)");

        var documentationDir = FILE.join("documentation");

        if (OS.system([FILE.join(documentationDir, "make_headers.sh")]))
            OS.exit(1); //rake abort if ($? != 0)

        if (!OS.system([doxygen, FILE.join(documentationDir, "CoreData.doxygen")]))
        {
            FILE.move("debug.txt", FILE.join("documentation", "debug.txt"));
        }

        OS.system(["ruby", FILE.join(documentationDir, "cleanup_headers")]);
    }
    else
        print("doxygen not installed. skipping documentation generation.");
});


task ("help", function()
{
    const app = jake.application().name();

    colorPrint("--------------------------------------------------------------------------", "bold+green");
    colorPrint("CoreData - Framework", "bold+green");
    colorPrint("--------------------------------------------------------------------------", "bold+green");

    describeTask(app, "debug", "Builds a debug version at " + path.join(buildDir, "Debug", productName));
    describeTask(app, "release", "Builds a release version at " + path.join(buildDir, "Release", productName));
    describeTask(app, "all", "Builds a debug and release version");
    describeTask(app, "install", "Builds a debug and release version, then installs in " + packageFrameworksPath);
    describeTask(app, "install-symlinks", "Builds a debug and release version, then symlinks the built versions into " + packageFrameworksPath);
    describeTask(app, "clean", "Removes the intermediate build files");
    describeTask(app, "clobber", "Removes the intermediate build files and the installed frameworks");
    describeTask(app, "test", "Runs all testcases at " + path.resolve("Test"));

    colorPrint("--------------------------------------------------------------------------", "bold+green");
});

CLEAN.include(buildPath);
CLOBBER.include(path.join(buildDir, "Debug", productName))
    .include(path.join(buildDir, "Release", productName))
    .include(debugPackagePath)
    .include(releasePackagePath)

const install = function(action)
{
    ["Release", "Debug"].forEach(function(aConfig)
    {
        colorPrint((action === "symlink" ? "Symlinking " : "Copying ") + aConfig + "...", "cyan");

        const thePackageFrameworksPath = aConfig === "Debug" ? path.join(packageFrameworksPath, aConfig) : packageFrameworksPath;

        if (fs.existsSync(thePackageFrameworksPath) && !fs.lstatSync(thePackageFrameworksPath).isDirectory())
            childProcess.execSync(["mkdir", "-p", thePackageFrameworksPath].map(utilsFile.enquote).join(" "));
        
        var buildPath = path.resolve(path.join(buildDir, aConfig, productName)),
            targetPath = path.join(thePackageFrameworksPath, productName);

        if (action === "symlink")
            directoryOp(["ln", "-sf", buildPath, targetPath]);
        else
            utilsFile.cp_r(buildPath, targetPath);
    });
};

const directoryOp = function(cmd)
{
    var targetPath = cmd[cmd.length - 1];

    if (fs.existsSync(targetPath) && fs.lstatSync(targetPath).isDirectory())
        childProcess.execSync(["rm", "-rf", targetPath].map(utilsFile.enquote).join(" "));

    childProcess.execSync(cmd.map(utilsFile.enquote).join(" "));
};

const describeTask = function(application, task, description)
{
    colorPrint("\n" + application + " " + task, "violet");
    description.split("\n").forEach(function(line)
    {
        stream.print("   " + line);
    });
};

const colorPrint = function(message, color)
{
    var matches = color.match(/(bold(?: |\+))?(.+)/);

    if (!matches)
        return;

    message = "\0" + matches[2] + "(" + message + "\0)";

    if (matches[1])
        message = "\0bold(" + message + "\0)";

    stream.print(message);
};
